include:
  - voicerooms/docker-compose.yml

services:
  postgres:
    image: postgres:15
    container_name: worldschat-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  backend:
    build:
      context: ./backend
    container_name: backend
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - app-network
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:1234@postgres:5432/db
      SECRET_KEY: your-secret-key-here
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "9000:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
